print("         ____")
print("        / >     >")
print("       |    -  -|")
print("       /'  = _x /")
print("     /          |")
print("      /   \     /")
print("    |     |  |  |")
print("   __       |  |  |")
print("  /--|     |  |  |")
print(" | (  \ ---\ --)---)")
print(" \ ---)")




print("-----------------------------")
print("Cat created by rupesh_hacker")
print("------------------------------")


c=input("do you want to quit?")
if c == 'yes':
    print(ok)